import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import DogIcon from '@/app/assests/icons/dog.svg';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="bg-primary flex flex-row justify-between h-12 items-center px-2">
        <h1 className="font-extrabold text-2xl">Pets!</h1>
        <DogIcon className="w-9 aspect-square"/>
      </nav>
        {children}
      </body>
    </html>
  );
}
